AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi
Globals:
  Function:
    Runtime: java17
    MemorySize: 512
    Timeout: 30

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: com.orders.aws.lambda.apis.CreateOrderLambda::createOrder
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  ReadOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: com.orders.aws.lambda.apis.ReadOrdersLambda::readOrders
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
